In [4]:
import pandas as pd
from xml.dom import minidom

# Reading the Data

In [20]:
platinum_df = pd.read_table('./data/matres/platinum.txt', header=None, sep='\t', names=['docid', 'verb1', 'verb2', 'eiid1', 'eiid2', 'relation'])
platinum_df[['eiid1', 'eiid2']] = 'e' + platinum_df[['eiid1', 'eiid2']].astype(str)

# Fixing a typo in the docid
platinum_df.loc[platinum_df['docid'] == 'nyt_20130321_sarcozy', 'docid'] = 'nyt_20130321_sarkozy'

platinum_df.head()

              docid       verb1     verb2 eiid1 eiid2 relation
0  WSJ_20130322_159  apologized  happened    e1    e5    VAGUE
1  WSJ_20130322_159  apologized   wrapped    e1    e6   BEFORE
2  WSJ_20130322_159  apologized    seemed    e1   e10   BEFORE
3  WSJ_20130322_159  apologized     yield    e1   e11    VAGUE
4  WSJ_20130322_159    happened   wrapped    e5    e6   BEFORE

In [21]:
unique_docids = platinum_df['docid'].unique()

doc_texts = {}
for docid in unique_docids:
    sample_filename = f"{docid}.tml"
    text_content = minidom.parse('./data/tempeval/' + sample_filename).getElementsByTagName('TEXT')[0]
    text_content_str = ''.join(node.toxml() for node in text_content.childNodes).strip()
    doc_texts[docid] = text_content_str

docs_df = pd.DataFrame(list(doc_texts.items()), columns=['docid', 'text'])
docs_df.head()

,docid,text
0,WSJ_20130322_159,Israeli Prime Minister Benjamin Netanyahu <EVE...
1,nyt_20130322_strange_computer,"Our <TIMEX3 type=""DATE"" value=""PRESENT_REF"" ti..."
2,CNN_20130321_821,"Barack Obama would <EVENT class=""OCCURRENCE"" e..."
3,nyt_20130321_cyprus,"A Cyprus <EVENT class=""OCCURRENCE"" eid=""e2001""..."
4,bbc_20130322_1353,"Israel's prime minister has <EVENT class=""OCCU..."